### ISSUE TITLE
Game Team Request: Shorter tokens

### ISSUE THREAD

**Issue by at-boy** [bornhack/bornhack-website#1048]
In the Game Team one issue in regards to the token game that have come up quite often is the lenght of tokens.

We would very much like to have the ability to create shorter tokens.

Right now the length is max 32 characters with a minimum of 31, would it maybe be possible to go down to 8 characters, so minimum is 8 and maximum is still 32.

**Comment by tykling** [comment]
I am concerned 8 might encourage bruteforcing. Maybe it is not a valid concern.

**Comment by at-boy** [comment]
That is definitely a valid concern and something that might happen.

Would 12 maybe be better?
