### ISSUE TITLE
Game Team Request: Token Game stats and leaderboard feed for the Metrics Team and users

### ISSUE THREAD

**Issue by at-boy** [bornhack/bornhack-website#1050]
It could be nice to have feeds from the token game system with stats and leaderbord that could be displayed in the bar and or other places.

Stats like a leaderboard where there is user info should be anonymous but maybe it should possible for users to opt-in to have their username displayed in the feed.

Ideas for stats that could be nice to have.
- [x] Leaderboard (num tokens found pr. user)
- [ ] First Found (stats pr. user showing how many tokens that user were the first to find)
- [x] Token (by how many users have a token been found)
- [x] Token finds over time (an extract of all token finds and their timestamps)

**Comment by tykling** [comment]
find metrics at https://www.bornhack.dk/metrics in prometheus / openmetrics format. prefixed with `bornhack_tokengame_` - example from local dev:

```
# HELP bornhack_tokengame_token_finds_total The total number of token finds by camp, user and token
# TYPE bornhack_tokengame_token_finds_total gauge
bornhack_tokengame_token_finds_total{camp="BornHack 2021",token_id="74",user_id="17",username="Administrator"} 1.0
bornhack_tokengame_token_finds_total{camp="BornHack 2021",token_id="75",user_id="17",username="Administrator"} 1.0
# HELP bornhack_tokengame_first_token_finds_total The tokens found for the first time
# TYPE bornhack_tokengame_first_token_finds_total gauge
bornhack_tokengame_first_token_finds_total{camp="BornHack 2021",token_id="75",user_id="17",username="Administrator"} 1.0
```
