### ISSUE TITLE
Missing approve button in event view for event proposals in backoffice

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#1090]
When looking at, for example, https://bornhack.dk/bornhack-2022/backoffice/proposals/events/74aa20fd-3e1c-4f00-86e1-90c8245f19d9/

Here the speaker proposal was approved, but the event proposal was not. In this view I have a Reject-button, but no Approve button. It would be very useful to have both to be able to review individual events while reading them instead of from the list of event proposals.

This is not blocking in any way and is purely a UX matter.

**Comment by ahf** [comment]
To show this with screenshots. On the speaker review panel, we have access to an "Approve SpeakerProposal" button in the bottom left corner.

![image](https://user-images.githubusercontent.com/36521/176704747-9f01c499-b733-41f9-8c8f-12c24baba470.png)

In the event proposal review panel, we only have access to a reject button there:

![image](https://user-images.githubusercontent.com/36521/176704785-d4a815ee-d7dc-484c-babb-81619bbeb049.png)

It would be useful to have access to an approve button there (or an indicator for why approval is not currently possible if any such condition is present. This could, for example, be that the given speaker proposal has yet to be approved).

**Comment by tykling** [comment]
I couldn't reproduce but I tried something, reopen if it is still an issue please :)
