### ISSUE TITLE
(Possible) cookie error

### ISSUE THREAD

**Issue by AuroraInbag** [bornhack/bornhack-website#11]
Scenarie (i Chrome): Åbner et browser vindue, logger ind som Bob. Åbner et nyt browser vindue (ikke ny fane, men nyt vindue). Logger ind som Ryan i det nye vindue. Beder den om at huske mig.

Går tilbage til det vindue hvor Bob er logget ind. Refresher siden. Er nu logget ind som Ryan istedet helt automatisk. Ikke noget med at blive smidt af/logget ud som Bob først. Er nu bare helt automatisk Ryan.

Højst sandsynligt ikke et stort problem...medmindre Ryan er en spade der logger på/opretter fra en offentlig computer. For medmindre man tjekker sin profil, er det ikke tydeligt at man ikke længere er Bob men nu Ryan istedet.

Helt tydeligt et cookie issue. Spørgsmålet er bare om det er værd at bruge tid på at skrive sig ud af.

**Comment by tykling** [comment]
har gjort brugernavnet man er logget ind som tydeligt i menuen, gør ellers ikke andet ved det :)
