### ISSUE TITLE
retina/HiDPI images

### ISSUE THREAD

**Issue by Ern-st** [bornhack/bornhack-website#118]
The logo & other images look blurry on devices with HiDPI screens. This could be remedied by embedding images with 2x resolution and scaling down to 50% in CSS. Or in the case of the logo maybe just use an SVG instead?

I'd love to help, but far as I can see the source files are not included in the repo? I presume that the logo exists in SVG format somewhere? 🎨

**Comment by tykling** [comment]
The source files are here: https://github.com/bornhack/assets/tree/master/2017-website

**Comment by Telling** [comment]
Closing this, as it was fixed in https://github.com/bornhack/bornhack-website/pull/121.
