### ISSUE TITLE
Add Signal Group info, when team member has been approved

### ISSUE THREAD

**Issue by blackthornedk** [bornhack/bornhack-website#1200]
**Is your feature request related to a problem? Please describe.**
There is no list of the team signal groups. After joining a team, it is not obvious if and how to join the relevant signal group.

**Describe the solution you'd like**
We should add info about the signal group, on the team page, visible for members.
We could also ass a join link for the group.

The Signal Volunteer Group Link could also be added.
Both links can be added to the email, that is sent, when a member joins a team.

**Comment by Easyjuhl** [comment]
The Signal Volunteer Group does not allow joining via Group Link yet.
