### ISSUE TITLE
Unable to disable two-factor authentication / change device

### ISSUE THREAD

**Issue by flokli** [bornhack/bornhack-website#1203]
**Describe the bug**
I'm unable to disable two-factor authentication, which is a requirement for being able to *change* the 2FA being used

**To Reproduce**
1. Log into your bornhack account.
2. Go to https://bornhack.dk/profile/two_factor/remove
3. Click the "Yes, I'm sure" button
4. Observe you end up getting asked again, and nothing happens.

**Expected behavior**
I'd have expected after clicking "Yes, I'm sure" that my 2FA would have been disabled, and I can recreate a new 2FA.

**Screenshots**
![image](https://user-images.githubusercontent.com/183879/200910912-de0d2d3a-e8ac-473b-aa2a-81d1580f2814.png)

**Desktop (please complete the following information):**
 - OS: NixOS 22.11
 - Browser Firefox
 - Version 106.0.3

**Comment by valberg** [comment]
This was due to the server time having drifted.

**Comment by valberg** [comment]
Okay so this is still an issue. Also reported through IRC.

**Comment by flokli** [comment]
Can confirm, this still doesn't work, the "Yes, I'm sure" button simply reloads the page without disabling 2FA.

**Comment by flokli** [comment]
Thanks, confirmed this works now!
