### ISSUE TITLE
Minor nitpicking

### ISSUE THREAD

**Issue by batmule** [bornhack/bornhack-website#13]
+ https://bornhack.dk/good-to-know/
    s/Current is 220V/Voltage is 230V/ eller bedre "Power is a standard European 230V supply with type C & K plugs (http://www.worldstandards.eu/electricity/plugs-and-sockets/)"

**Comment by valberg** [comment]
Fixed in https://github.com/bornhack/bornhack-website/commit/2dd8d38d3577240fc7462b2caf39c02e3e6892ff
