### ISSUE TITLE
Change '#' in banktransfer instructions

### ISSUE THREAD

**Issue by batmule** [bornhack/bornhack-website#1384]
Too many participants report issues using '#' in the banktransfer message.

Example:
12:03:04 < the0> hi, I just tried to transfer moneys via bank transfer, and hit a few snags:
12:04:09 < the0> 1) the #-sign is not allowed in the description field - I hope your software does not depend on it

I suggest changing the instruction "Reference*: bornhack #2614" to "Reference*: bornhack BH2614"

**Comment by flummer** [comment]
Alternatively it could be "Reference*: order 2614", as "bornhack" is not important on our side (everything is bornhack). The number is an order number and not an invoice number, but we could and do also receive payments for invoices.

**Comment by batmule** [comment]
Fixed
