### ISSUE TITLE
Remove event icons from speaker in event listing

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#1398]
When observing the program at https://bornhack.dk/bornhack-2023/program/ the column called "Who?" shows a number of icons representing each type of each event a given event host have to the right of the name. This takes up a lot of space and is confusing to look at.

Let's remove them, but keep the icon in the "Type" column as it is today.

<img width="1577" alt="Screenshot 2023-07-23 at 14 34 04" src="https://github.com/bornhack/bornhack-website/assets/36521/651b8277-243b-4353-882b-9727feb9db16">

**Comment by ahf** [comment]
This is particularly visible for the Kramse, BornHack Game Team and PROSA hosts.

**Comment by 0xUnicorn** [comment]
@ahf - when I go to the URL, this is the view I get. I've tried finding the view from your screenshot but with no luck.

![image](https://github.com/bornhack/bornhack-website/assets/17219001/91f06ba5-9bf6-42ff-b463-8837c09b6f79)

I was thinking about changing the icons from the speakers page to a small badge indicating amount of events for each speaker. https://bornhack.dk/bornhack-2023/program/speakers/

![image](https://github.com/bornhack/bornhack-website/assets/17219001/b595e2fb-ff52-42fa-9206-2d1fd5d219db)
