### ISSUE TITLE
Issues related to the schedule

### ISSUE THREAD

**Issue by valberg** [bornhack/bornhack-website#149]
This is were I will gather stuff that needs to be done with the schedule.

- [ ] Add hovering to type filters (this might require http://package.elm-lang.org/packages/jinjor/elm-inline-hover/latest or something similar.)
- [ ] Figure out a way to present talks with long titles better in the day view.
- [ ] Choose a day -> Click a talk -> Day picker now marks "All days" as active. Idea: Implement a "last url" and even go further and implement breadcrumbs.
- [ ] Directly accessing an event makes the "back" button a bit redundant - this should be rethought.

Ongoing: Code cleanup - there is bound to be stuff that can be refactored into reusable code!

If you have found anything odd with the schedule, please add a comment. If you can provide a screenshot or a fix even better! :)

**Comment by valberg** [comment]
@zeltophil You mean in the overview and day views?

**Comment by zeltophil** [comment]
@valberg yes

**Comment by zeltophil** [comment]
There should be a column for each workshop room so that the workshops aren't displayed as overlapping and it becomes clear where each workshop is taking place.

**Comment by valberg** [comment]
I'm working on a complete rewrite of the schedule overview. So closing this for now.
