### ISSUE TITLE
Links on Info page open in same window

### ISSUE THREAD

**Issue by AuroraInbag** [bornhack/bornhack-website#15]
https://wwwstaging.bornhack.org/good-to-know/ All links on this site opens up in the same window. If this is not intentional, maybe consider that links going out of the Bornhack site, opens up in a new window.

**Comment by valberg** [comment]
Fixed in https://github.com/bornhack/bornhack-website/commit/2dd8d38d3577240fc7462b2caf39c02e3e6892ff
