### ISSUE TITLE
sponsor logos should not be an absolute url, should be without hostname so .onion serving doesn't suffer

### ISSUE THREAD

**Issue by tykling** [bornhack/bornhack-website#151]

**Comment by valberg** [comment]
I guess this requires us to change the `Sponsor.logo` from `URLField` to `FileField` (which is a good thing!) :) Whaddya think @tykling ?

**Comment by tykling** [comment]
:+1:

**Comment by tykling** [comment]
I always felt like UrlField should support relative URLs, but that is outside the scope of this issue :)

**Comment by tykling** [comment]
this issue can be closed, these changes are already in production
