### ISSUE TITLE
Add 2FA

### ISSUE THREAD

**Issue by netravnen** [bornhack/bornhack-website#157]
**Request:** Add 2FA to website login page.
* Do strong encouragement for all registered users on the website to use 2FA.

**Possible reasons why to consider this feature:**
* Added security.
* Promotes recommended security practices.

**Comment by valberg** [comment]
This should be fairly straight forward to implement using https://github.com/percipient/django-allauth-2fa

**Comment by Ern-st** [comment]
I'll give it a go over Christmas 🎅

**Comment by valberg** [comment]
Fixed in https://github.com/bornhack/bornhack-website/commit/aa704bc4db44b91f7274c8d0820a385e99998bfd
