### ISSUE TITLE
Onion addr på contact side

### ISSUE THREAD

**Issue by batmule** [bornhack/bornhack-website#16]
Vores .onion addr er ikke på contact siden, kun på forsiden.

You are very welcome to ask questions and show your interest on IRC at #bornhack on 6nbtgccn5nbcodn3.onion or irc.baconsvin.org, both using TLS on port 6697.

vs

Hit us up on IRC at #bornhack @ irc.baconsvin.org (TLS port 6697)

**Comment by valberg** [comment]
Fixed in https://github.com/bornhack/bornhack-website/commit/d12ab4444a8dff093090caa1a0726bc134153fb6
