### ISSUE TITLE
Calendar events contain invalid URL

### ISSUE THREAD

**Issue by flimpie** [bornhack/bornhack-website#1614]
The description of individual calendar events contains a link to the event page on the BornHack website.

However, it is incorrectly formatted, resulting in a URL that looks like `https://bornhack.dk//bornhack-2024/some-event/`, which, probably due to the double slashes after `bornhack.dk`, results in a 404.

![image](https://github.com/user-attachments/assets/c22abc80-2650-44f2-8d49-8a7ea159bf8f)

**Comment by tykling** [comment]
thanks! :D
