### ISSUE TITLE
make bar products a CampRelatedModel

### ISSUE THREAD

**Issue by tykling** [bornhack/bornhack-website#167]
add a foreignkey to Camp, subclass CampRelatedModel, to maintain history and goodness

**Comment by valberg** [comment]
@tykling `bar.models.ProductCategory` is a `CampRelatedModel` and has a FK to `Camp`. Shouldn't that be enough? Or am I missing something? :smiley:

**Comment by valberg** [comment]
@tykling Closing this. Feel free to reopen if it is still an issue :)
