### ISSUE TITLE
Show speaker proposals before new proposals in Submit Proposal page

### ISSUE THREAD

**Issue by juga0** [bornhack/bornhack-website#259]
When a new proposal is created, the landing page is Submit Proposal again, showing only at the bottom the  list of existing speaker proposals. If the user does not scroll down, they can think the proposal has not been created.
I think this can be solved switching the order of ``{% if camp.call_for_participation_open %}`` and ``{% if speakerproposal_list or eventproposal_list %}`` in ``proposal_list.html``

**Comment by tykling** [comment]
:+1:
