### ISSUE TITLE
Show location of event on the event description page

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#261]
The location should ideally be shown both on:

https://bornhack.dk/bornhack-2018/program/making-rest-api-in-sinatra-with-automation-tests-in-bash/

and

https://bornhack.dk/bornhack-2018/program/#/event/making-rest-api-in-sinatra-with-automation-tests-in-bash (under the metadata section)

This should allow people to more easily figure out where things are.

**Comment by valberg** [comment]
Aaand https://github.com/bornhack/bornhack-website/commit/56875732ddb5c28be868023fb1b5823efb008a5f
