### ISSUE TITLE
Add RSS feed of news items

### ISSUE THREAD

**Issue by zeltophil** [bornhack/bornhack-website#262]
Not everyone uses twitter. It would be great to be able to subscribe to BornHack news via RSS.

**Comment by valberg** [comment]
Closed by https://github.com/bornhack/bornhack-website/commit/92a5f67ae31c7746b420dfda70c095779b89cb46 (just need to add a link somewhere - incoming!)

**Comment by valberg** [comment]
https://bornhack.dk/news/feed is the URL btw.
