### ISSUE TITLE
Missing information in content backoffice system

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#289]
When I go to the content team backoffice system I'm missing the following information that the speaker is adding as part of their submissions:

1. The "event notes".
2. The "event duration".

It would be useful to see the email address of the submitting user under the "Manage Speaker Proposal" page as well. It's currently listed in the table in the "overview of proposals" view.

**Comment by valberg** [comment]
Fixed in https://github.com/bornhack/bornhack-website/commit/0b6cc60bb8d0fa6da336c20eccea4bad7c05c0ec
