### ISSUE TITLE
Create an "outbox" for emails sent to speakers

### ISSUE THREAD

**Issue by valberg** [bornhack/bornhack-website#297]
I've just been working with pretalx for DjangoCon Europe 2019 - and it has an very simple but yet awesome feature where all mails sent to speakers are put in an outbox so the content team has an option to edit mails before they are sent.

Stuff like:
- Your talk has been accepted/rejected
- Your talk has been scheduled for this timeslot

It think this might be a very nice feature to get as well - what do you thing @ahf ?

**Comment by tykling** [comment]
we have this now, including backoffice view to edit and release mails
