### ISSUE TITLE
Make schedule available in frab XML format

### ISSUE THREAD

**Issue by zeltophil** [bornhack/bornhack-website#336]
Many people already use apps like Giggity that display event schedules. Giggity understands various XML formats, for example frab XML. Using this format might also make it easier when using part of the VOC infrastructure for publishing recordings.

**Comment by tykling** [comment]
auth schema: https://raw.githubusercontent.com/wiki/frab/frab/images/schedule.xsd and https://github.com/frab/frab/blob/master/app/views/public/schedule/index.xml.haml

pretalx implementation: https://github.com/pretalx/pretalx/blob/d44f67f0452fe0fdf7336b694790e9604381cc48/src/pretalx/schedule/exporters.py#L90-L105

**Comment by tykling** [comment]
Using FOSDEM frab xml as an example might be a bad idea, it contains a `day_change` element which is not in the XSD https://fosdem.org/2020/schedule/xml

**Comment by tykling** [comment]
https://wwwstaging.bornhack.org/bornhack-2019/program/frab.xml
