### ISSUE TITLE
Schedule view

### ISSUE THREAD

**Issue by zeltophil** [bornhack/bornhack-website#340]
In the schedule overview and the day views the speaker name should be displayed. Also in the day view as many lines as fit in the box should be displayed. Currently there are only two lines before the title is cut off, even when the box is big enough.

**Comment by tykling** [comment]
@valberg this seems like your neck of the woods, if I understand the issue correctly :)

**Comment by valberg** [comment]
This is for the old elm based schedule if I understand it correctly. Closing.
