### ISSUE TITLE
Possibility to create "Looking for ride" post in ride sharing

### ISSUE THREAD

**Issue by valberg** [bornhack/bornhack-website#343]

**Comment by zeltophil** [comment]
The rideshare form also needs a contact field. It would be great if the list of rides would be sortable.

**Comment by tykling** [comment]
The rideshare page has been shined up a bit. You now specify both from and to, and whether you have seats or are looking for a ride.

**Comment by tykling** [comment]
The rideshare details page already has a contact form

**Comment by tykling** [comment]
and it is not also sortable
