### ISSUE TITLE
Diverse stavefejl/rettelser

### ISSUE THREAD

**Issue by AuroraInbag** [bornhack/bornhack-website#36]
https://bornhack.dk/info/

Under Bar Area:
Is: "The bar area is the place to go when you a all hacked out...", Should be: "The bar area is the place to go when you are all hacked out..."

Under Info Desk:
Is: "Info desk: Qestions and information about anything and everything", Should be: "Info desk: Questions and information about anything and everything"

https://bornhack.dk/shop/products/one-day-ticket:

One day ticket text:
Is: "One day ticket for friday which grants you access the event...", Should be: "One day ticket for friday which grants you access to the event..."

**Comment by tykling** [comment]
fixet, tak
