### ISSUE TITLE
Make event locations in the schedule day view ordered by weight

### ISSUE THREAD

**Issue by zeltophil** [bornhack/bornhack-website#364]
Currently in the day view of the schedule the event locations are sorted by the time they were last edited. It would be nice to add a weight for ordering by.

**Comment by valberg** [comment]
Would an alphabetical sorting be alright, or is there an argument for adding a "weight" attribute to locations? @zeltophil

**Comment by zeltophil** [comment]
You probably want to list the speakers tent first, then the workshop areas. Then maybe what has most content, or after the times that events are happening (e.g. outside during the day vs. in the bar area in the evening). We might also have more than one location for talks in the future.

**Comment by valberg** [comment]
I guess this is also for the old elm based schedule - closing.
