### ISSUE TITLE
fix ordering of products, perhaps a clientside sorting thing is easiest

### ISSUE THREAD

**Issue by tykling** [bornhack/bornhack-website#38]

**Comment by valberg** [comment]
@tykling https://github.com/bornhack/bornhack-website/commit/94234b4294e58ce10e22344f22c67fa65dd008c7 might do the trick!

**Comment by valberg** [comment]
https://github.com/bornhack/bornhack-website/commit/94234b4294e58ce10e22344f22c67fa65dd008c7 did the trick
