### ISSUE TITLE
Event owners should receive an email when their talk is accepted, rejected, and scheduled

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#384]
It would be useful if the submitter of an event receives an email when their talk is accepted, rejected, and scheduled in the program.

Additionally I would like a text input field when a talk is accepted/rejected called "Reason". If this field is empty it should not be mentioned in the email, but if the field is non-empty it should be included in the email.

**Comment by tykling** [comment]
see also #297

**Comment by tykling** [comment]
@ahf the user should get a new mail if we re-schedule, right?

**Comment by tykling** [comment]
clarified on irc: yes, the user and speakers should get a new email if we reschedule
