### ISSUE TITLE
Event owners should be able to specify available dates and time when submitting content

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#385]
It would be useful if people submitting content MUST specify their availability using a small calendar and time widget. By default this one should be set for the entire week (minus day #0 - the hello world day, but including the goodbye world day). The days + time with content could be specified as a range on the Camp object I think, but that is an implementation detail for you guys to solve.

**Comment by ahf** [comment]
Bonus points if the Event Instance objects can validate this such that the content team cannot create an event instance outside of the range specified for the given event.

**Comment by tykling** [comment]
we have this now
