### ISSUE TITLE
Content submittors that is recorded should accept a license (of our choice?)

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#406]
We should add an additional checkbox that says something in the line of "I accept that the video of my talk can be published under the X license". If a user has "yes" to record, but "no" to this, we should record it, but probably not publish it?

X is probably some creative commons license.

We should talk with some orgs that we work with how they handle this.

**Comment by tykling** [comment]
EMF uses https://creativecommons.org/licenses/by-sa/4.0/ and they just avoid recording if the user cannot accept the license.

Would you prefer two seperate checkboxes, one for recording y/n and one for license accept y/n or should we just keep the one checkbox and change the wording on it to mention the license?

**Comment by tykling** [comment]
@ahf what do you think?

**Comment by tykling** [comment]
clarified on irc, we only want one checkbox, and if speaker cant accept the license we will not record it

**Comment by tykling** [comment]
fixed in 24d2c0d041bfcb0a4a7660688974eb4d01813d3d
