### ISSUE TITLE
clean up old branches

### ISSUE THREAD

**Issue by tykling** [bornhack/bornhack-website#447]
we have so many old branches, a cleanup would be nice

**Comment by flummer** [comment]
I have removed the `2019letterhead` and `2020logo` branches, both was already merged in.

**Comment by flummer** [comment]
Same with `bank-transfer-info` and `sponsors`

**Comment by valberg** [comment]
I just removed all mine that were merged in.

**Comment by flummer** [comment]
I have removed a few more (already merged) and I think the remaining are active to some degree (attached to an open PR or being worked on)
