### ISSUE TITLE
Changes to the input fields for the content sign up form

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#467]
People seems to misunderstand our content submission form and submits things in the wrong fields. I would like to propose the following changes:

1. Move description label of each input field to be on top of the form and below the title instead of below the form.
2. Change the label with "The description/abstract of this talk/presentation. Explain what the audience will experience." to "The description/abstract of this talk/presentation. Explain what the audience will experience. This information will be publicly available on the website."
3. Change title from "Talk Notes" to "Notes to the Content Team". For debates this one is called "Debate Act Notes".
4. Change the label with "Private notes regarding this talk. Only visible to yourself and the BornHack organisers." to "Private notes regarding this talk. Only visible to yourself and the BornHack content team. Example: For my (panel debate|talk) I will need access to 2 tables, 4 chairs, 4 microphones, and ideally some coffee/water available for the participants of the debate.". 

(1) applies to all submission types, (2) + (3) + (4) applies for talks, lightning talks, and panel debates, but panel debates have slightly different titles for the headlines, but the conceptual change is the same.

**Comment by ramarrom** [comment]
As part of this we need to replace some of the django-bootstrap templates, so I suggest to upgrade bootstrap before we do this.
