### ISSUE TITLE
Fix issue with python version in manage.py shebang

### ISSUE THREAD

**Issue by flummer** [bornhack/bornhack-website#474]
The shebang doesn't seem to follow the virtualenv so when called without the correct python in front of the command, weird stuff can happen (missing modules, even though it seems like they are there.

README.md should also be updated to include the virtualenv python version in the commands

**Comment by tykling** [comment]
you can remove the shebang line from manage.py to force people to use python to execute it

**Comment by tykling** [comment]
the shebang line in manage.py is just `#!/usr/bin/env python` which should be exactly the same as running "python manage.py" ... weird

**Comment by tykling** [comment]
@valberg do you have any ideas on what might be causing this? removing the shebang line is fine with me, but it seems like this might be a local issue on @flummer laptop?

**Comment by flummer** [comment]
It is probably a local issue, closing this.
