### ISSUE TITLE
Info on strict Danish radio laws

### ISSUE THREAD

**Issue by batmule** [bornhack/bornhack-website#61]
We should probably have something on the webpage

From #bornhack
10:10:47 < hmf      > Can you setup a GSM network in the GSM/USA band range as well as europe's GSM bands?
10:11:32 < hmf      > If you're doing that with SDR?  I can help... in fact, I have 8 USRPs, and two BladeRFs.. all working, with daughterboards (wideband) for the old-style USRPs.
10:11:57 < jok      > hmf, you have to have a test license or a license from an operator to legally be able to use GSM/UMTS/LTE bands in denmark
10:11:59 < hmf      > Tons of antennas, omni and directional (log-periodic, pcb-based, and not.. heh)
10:12:16 < hmf      > Oh... Really though?  For a small network 
10:12:21 < hmf      > for a short time
10:12:23 < jok      > yes
10:12:39 < hmf      > Can I get the short time period license
10:12:47 < hmf      > apply for it from the US?
10:13:11 < jok      > you could probably apply for on
10:13:21 < hmf      > I definitely want to use SDRs when I'm in country
10:13:26 < hmf      > werd
10:13:40 < jok      > but to my knowledge, you'll likely not get a test license due to all the bands being allocated
10:13:57 < hmf      > jok: UMTS/LTE? Are you guys running UMTS/LTE networks?
10:13:58 < jok      > the best you could do was to get one of the 3 network carriers to let you use some of their spectrum
10:14:38 < hmf      > Do you have basebands to do so?  Software side of the baseband?  I wish Osmo\* and/or OpenBSC/BTS woulddevelop *CDMA and *LTE/LTE-A baseband code.
10:14:40 < jok      > hmf, not likely, but the law applies for all bands used for commercial purposes where someone owns a license
10:15:30 < hmf      > ahh, yeah I really would love to see CDMA, LTE/LTE-A actually attempted in open-source.  I think there has to be enough interest with the compounding of CDMA and LTE both not only doing cellular/mobile
10:15:49 < hmf      > but also, having S-CDMA and S-LTE here, as DOCSIS channel encapsulators
10:16:03 < hmf      > RF over Coaxial cable
10:16:16 < jok      > well, danish law is very prohibitive of using licensed spectrum unlicensed

**Comment by tykling** [comment]
feel free to add this info as an InfoItem using the Django admin, closing issue
