### ISSUE TITLE
URL's in Markdown should automatically be clickable

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#64]
The dialect we use of markdown currently doesn't automatically make 'http://foo.com/' URL's clickable. It would be useful to have.

**Comment by benjaoming** [comment]
This should be easy to fix -- it's a template filter we can chain to the markdown filter, AFTER converting to HTML... I'm sure it's smart enough not to convert `<a href="http://">` to `<a href="`<a href="http://">`">` :)

https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#urlize

**Comment by flummer** [comment]
It seems like the urlize filter will mess up HTML links as per the note on https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#urlize so something else is needed

**Comment by benjaoming** [comment]
Try a Markdown extension: https://github.com/r0wb0t/markdown-urlize
