### ISSUE TITLE
Show email address instead of username for users

### ISSUE THREAD

**Issue by ahf** [bornhack/bornhack-website#647]
In a lot of places in the backoffice, we show the "username". The username is the username part of the email address. Many of our participants uses bornhack@theirowndomain.whatever and thus have "bornhack1", "bornhack2", etc. as username. It would be nice to just display their email address instead.

**Comment by ramarrom** [comment]
I have checked what needs changing.

These pages currently have both user name and email address.

* /bornhack-2023/backoffice/feedback/facilities/power/
* /bornhack-2023/backoffice/feedback/facilities/sanitation/
* /bornhack-2023/backoffice/infodesk/orders/
* /bornhack-2023/backoffice/speakers/
* /bornhack-2023/backoffice/merchandise_orders/
* /bornhack-2023/backoffice/village_orders/
* /bornhack-2023/backoffice/tokens/46/
* /bornhack-2023/backoffice/tokens/stats/

These pages currently have only user name.

* /bornhack-2023/backoffice/economy/expenses/
* /bornhack-2023/backoffice/economy/reimbursements/
* /bornhack-2023/backoffice/economy/revenues/

**Comment by tykling** [comment]
:+1:
