### ISSUE TITLE
Questionnaire

### ISSUE THREAD

**Issue by valberg** [bornhack/bornhack-website#7]
We should be able to ask a ticket owner (not necessarily the same as the ticket buyer) various questions.

One way of doing this is to have a questionnaire which is tied to a `Ticket`. This way we can have a direct URL (using the token of the ticket) which can be given to the ticket owner without him/her having to login.

**Comment by tykling** [comment]
do we still need this?

**Comment by valberg** [comment]
I don't believe so :) Closing.
