### ISSUE TITLE
New sorting of event types on https://bornhack.dk/bornhack-2021/program/proposals/

### ISSUE THREAD

**Issue by fonsmark** [bornhack/bornhack-website#735]
This is not a very important issue, but it would be nice to change the sorting on the page: https://bornhack.dk/bornhack-2021/program/proposals/

This is my proposed order:
Talk
Lightning Talk
Workshop
Debate
Meetup
Music Act
Recreational Event

**Comment by ramarrom** [comment]
I propose to close this.
