### ISSUE TITLE
Add option for village owners to place themselves on the map

### ISSUE THREAD

**Issue by ghost** [bornhack/bornhack-website#876]
- [ ] It would be neat if village owners could add their villages to the map by entering the GPS coords on their village page once they have set up camp. 

- [ ] Perhaps it should be limited to people who have checked in their ticket so we don't have villages "reserving" spaces before they arrive.

**Comment by tykling** [comment]
We dont know which of the logged-in users tickets belongs to the logged-in user and which belong to their friends/children/whatever, so limiting to checked-in users is not trivial
