### ISSUE TITLE
Content : Add statement saying that HAX are not refundable.

### ISSUE THREAD

**Issue by WilliamBenEmbarek** [bornhack/bornhack-website#881]
Several people have asked in the info desk if they can refund HAX, this should be more clear on the website

**Comment by valberg** [comment]
There is a note about it on https://bornhack.dk/bornhack-2022/info/#hax - but maybe a sign in the infodesk also could make it more clear.

**Comment by zeltophil** [comment]
There are signs at the infodesk now.
